### ISSUE TITLE
TODO-PLUS-FIXME-ton

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/clair#38]
There is a sizeable number of detailed TODO's and FIXME's in the clair code; 
propose to make a plan to tackle these one-by-one:

* [ ] create a list of TODO's and FIXME's in the code of Clair and list them here.
* [ ] fix each TODO and FIXME, possibly adding test cases for the newly covered features
* [ ] release a new version of clair
